version: "3.2"
services:
  rest:
    image: catalogicsoftware/dpx-rest:${TAG_REST}
    env_file:
     - ./dpx.env
    environment:
      - _JAVA_OPTIONS=-Dlogging.level.com.catalogic.dpx.rest.commons.DBConn=DEBUG -Dauth.server.public.key.file.path=/key/catalogic.pub
      - DPX_MAX_CONNECTIONS_PER_USER=6
      - SPRING_DATASOURCE_URL=jdbc:postgresql://sql-db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=secret
    deploy:
      replicas: 1
    ports:
      - "8080:8080"
    volumes:
      - "./opt-apigateway:/key"
      - "./opt-apigateway:/opt"
    networks:
      - "webnet"
    depends_on:
      - "sql-db"
    logging:
      driver: "fluentd"
      options:
        tag: dpx-rest
  sql-db:
    image: postgres:11
    deploy:
      replicas: 1
    ports:
      - target: 5432
        published: 5433
        protocol: tcp
        mode: host
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - "./rest-db:/var/lib/postgresql/data/pgdata"
    networks:
      - "webnet"
    logging:
      driver: "fluentd"
      options:
        tag: dpx-sql-db
  vplugin-mgr:
    image: catalogicsoftware/dpx-vplugin-mgr:${TAG_VPLUGIN_MGR}
    env_file:
     - ./dpx.env
     - ./dpx-vplugin-mgr.env
    environment:
      - AUTH_SERVER_URL=http://auth:8081
      - SVC_SERVER_URL=http://rest:8080
      - S3_BUCKET_FOLDER_NAME=released
      - LOCAL_PLUGIN_FOLDER=plugins/
    deploy:
      replicas: 1
    ports:
      - "8082:8082"
    volumes:
      - "./plugins:/app/plugins"
    networks:
      - webnet
    logging:
      driver: "fluentd"
      options:
        tag: dpx-vplugin-mgr
  auth:
    image: catalogicsoftware/dpx-auth:${TAG_AUTH}
    env_file:
     - ./dpx.env
    deploy:
      replicas: 1
    ports:
      - "8081:8081"
    volumes:
      - "./opt-auth/catalogic.jks:/opt/catalogic.jks"
    networks:
      - webnet
    logging:
      driver: "fluentd"
      options:
        tag: dpx-auth
  config-ui:
    image: catalogicsoftware/dpx-ui:${TAG_UI}
    deploy:
      replicas: 1
    ports:
      - "8088:8088"
    networks:
      - webnet
    logging:
      driver: "fluentd"
      options:
        tag: dpx-config-ui
  apigateway:
    image: catalogicsoftware/dpx-apigateway:${TAG_APIGATEWAY}
    env_file:
     - ./dpx-apigateway.env
    environment:
        - zuul_routes_app_url=http://rest:8080/
        - zuul_routes_auth_url=http://auth:8081/
        - zuul_routes_plugin_mgr_url=http://vplugin-mgr:8082/
        - zuul_routes_config_ui_url=http://config-ui:8088/
        - SOCKET_TIMEOUT_MILLIS=120000
    deploy:
      replicas: 1
    ports:
      - "80:8085"
      - "443:443"
    volumes:
      - "./opt-apigateway:/opt"
    networks:
      -  webnet
    logging:
      driver: "fluentd"
      options:
        tag: dpx-apigateway
  fluentd:
    image: fluent/fluentd:v1.4-1
    volumes:
      - "./config/fluent.conf:/fluentd/etc/fluent.conf"
      - "./stack-logs:/fluentd/log"
    ports:
      - "24224:24224"
    networks:
      - webnet
networks:
    webnet:
